server:
  port: 10010
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
mall:
  db:
    database: item-service
  swagger:
    title: 易购商城商品服务接口文档
    desc: 易购商城接口文档
    package: com.study.item.controller
