server:
  port: 10040
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
mall:
  db:
    database: user-service
  swagger:
    title: 易购商城购物车服务接口文档
    desc: 易购商城接口文档
    package: com.study.user.controller
ebuy:
  jwt:
    location: classpath:eBuy.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123
