server:
  port: 10030
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
mall:
  db:
    database: pay-service
  swagger:
    title: 易购商城订单服务接口文档
    desc: 易购商城接口文档
    package: com.study.pay.controller
